# Generated by Django 2.2.4 on 2023-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20231125_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
