# Generated by Django 2.2.4 on 2023-11-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_file',
            field=models.ImageField(null=True, upload_to='movie_images/'),
        ),
    ]
